<!-- <h2>hello</h2> -->
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \PurpleCommerce\ProductEnquiry\Block\Index $block */
?>
<?php
    if($block->isModuleEnabled()){ 
        if($block->isOnDetail()){
            if($block->isForAll()){
                echo $block->getPopup();
            }else{
                $categories=$block->visibleCategories();
                $categories = explode(',',$categories);
                $currentProduct=$block->getCurrentProduct();
                $currentCat=$currentProduct->getCategoryIds();
                // echo "here";
                // echo '<pre>';
                // print_r($categories);
                // echo '<pre>';
                // print_r($currentCat);
                $result=array_intersect($categories,$currentCat);
                // echo '<pre>';
                // print_r($result);
                if(count($result)>0){
                    echo $block->getPopup();
                }
            }
        }else{

        }
    }else{
        echo 'no';
    }

?>
    